# Generated by Django 4.1.2 on 2023-01-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(help_text='Подробно опишите событие и расскажите про выступающих', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(help_text='Подробно опишите событие и расскажите про выступающих', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Подробно опишите событие и расскажите про выступающих', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='photos/events', verbose_name='Фото'),
        ),
    ]
